# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"
  - "3.4"

# Anaconda information comes from https://gist.github.com/dan-blanchard/7045057
# Setup anaconda
before_install:
- git config --global user.name "Travis"
- git config --global user.email "travis@travis.com"

# Install packages
install:
  - python setup.py install

# Run tests
script:
  - python setup.py test